import Head from 'next/head';
import CardsList from '../components/CardsList';
import HeroImage from '../components/HeroImage';


export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Karvy Infotech | Technical Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroImage />
        <div className="container p-5 mx-auto bg-red-800 my-52 rounded-xl">
          <CardsList/>
        </div>
      </main>
    </div>
  )
}
